/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author paulo
 */
public class GUIPilha extends javax.swing.JFrame {
    private Pilha pilha = new Pilha();

    /**
     * Creates new form Pilha
     */
    public GUIPilha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfItem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbPush = new javax.swing.JButton();
        jbPop = new javax.swing.JButton();
        jbPrint = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jbMaximo = new javax.swing.JButton();
        jbMinimo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtfPilha = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pilha");
        setResizable(false);

        jLabel1.setText("Item:");

        jLabel2.setText("Display:");

        jbPush.setText("PUSH");
        jbPush.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPushMouseClicked(evt);
            }
        });

        jbPop.setText("POP");
        jbPop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPopMouseClicked(evt);
            }
        });

        jbPrint.setText("PRINT");
        jbPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPrintMouseClicked(evt);
            }
        });

        jbSair.setText("SAIR");
        jbSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSairMouseClicked(evt);
            }
        });

        jbMaximo.setText("MÁXIMO");
        jbMaximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbMaximoMouseClicked(evt);
            }
        });
        jbMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMaximoActionPerformed(evt);
            }
        });

        jbMinimo.setText("MÍNIMO");
        jbMinimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbMinimoMouseClicked(evt);
            }
        });

        jtfPilha.setColumns(20);
        jtfPilha.setRows(5);
        jScrollPane3.setViewportView(jtfPilha);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbPush, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbPop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbMaximo)
                            .addComponent(jbMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbMaximo, jbMinimo, jbPop, jbPrint, jbPush, jbSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbPush)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbPop)
                            .addComponent(jbMaximo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbPrint)
                            .addComponent(jbMinimo))
                        .addGap(13, 13, 13)
                        .addComponent(jbSair))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPushMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPushMouseClicked
        // TODO add your handling code here:
        int item;
        item = Integer.parseInt(jtfItem.getText());
        pilha.push(item);
        System.out.println("Empilhei o " + item);
    }//GEN-LAST:event_jbPushMouseClicked

    private void jbPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPrintMouseClicked
        // TODO add your handling code here:
        pilha.printConsole();
        String texto;
        texto = pilha.printSwing();
        jtfPilha.setText(texto);
    }//GEN-LAST:event_jbPrintMouseClicked

    private void jbPopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPopMouseClicked
        // TODO add your handling code here:
        pilha.pop();
    }//GEN-LAST:event_jbPopMouseClicked

    private void jbSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbSairMouseClicked

    private void jbMaximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMaximoMouseClicked
        // TODO add your handling code here:
        int max = pilha.maximoElemento();
        String txt = Double.toString(max);
        jtfPilha.setText(txt);
    }//GEN-LAST:event_jbMaximoMouseClicked

    private void jbMinimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMinimoMouseClicked
        // TODO add your handling code here:
        int min = pilha.minimoElemento();
        String txt = Double.toString(min);
        jtfPilha.setText(txt);
    }//GEN-LAST:event_jbMinimoMouseClicked

    private void jbMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMaximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMaximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPilha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPilha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbMaximo;
    private javax.swing.JButton jbMinimo;
    private javax.swing.JButton jbPop;
    private javax.swing.JButton jbPrint;
    private javax.swing.JButton jbPush;
    private javax.swing.JButton jbSair;
    private javax.swing.JTextField jtfItem;
    private javax.swing.JTextArea jtfPilha;
    // End of variables declaration//GEN-END:variables
}
