/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author paulo
 */
public class GuiPilha2 extends javax.swing.JFrame {

        Pilha pilha = new Pilha();
    /**
     * Creates new form GuiPilha2
     */
    public GuiPilha2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaPilha = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jtfElemento = new javax.swing.JTextField();
        jbPush = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jbPop = new javax.swing.JButton();
        jbPrint = new javax.swing.JButton();
        jbMax = new javax.swing.JButton();
        jbMin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pilha Generator");

        jtaPilha.setColumns(20);
        jtaPilha.setRows(5);
        jScrollPane1.setViewportView(jtaPilha);

        jLabel1.setText("Elemento");

        jbPush.setText("PUSH");
        jbPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPushActionPerformed(evt);
            }
        });

        jbSair.setText("SAIR");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jbPop.setText("POP");
        jbPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPopActionPerformed(evt);
            }
        });

        jbPrint.setText("PRINT");
        jbPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrintActionPerformed(evt);
            }
        });

        jbMax.setText("MÁXIMO");
        jbMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMaxActionPerformed(evt);
            }
        });

        jbMin.setText("MÍNIMO");
        jbMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtfElemento, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(0, 101, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbPush)
                                    .addComponent(jbPop)
                                    .addComponent(jbPrint)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbMin)
                                    .addComponent(jbMax)
                                    .addComponent(jbSair)))))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbMax, jbMin, jbPop, jbPrint, jbPush, jbSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbPush)
                        .addGap(18, 18, 18)
                        .addComponent(jbPop)
                        .addGap(18, 18, 18)
                        .addComponent(jbPrint)
                        .addGap(18, 18, 18)
                        .addComponent(jbMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jbMin)
                        .addGap(18, 18, 18)
                        .addComponent(jbSair)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPushActionPerformed
        // TODO add your handling code here:
        pilha.Push((Integer.parseInt(jtfElemento.getText())));
    }//GEN-LAST:event_jbPushActionPerformed

    private void jbPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPopActionPerformed
        // TODO add your handling code here:
        pilha.Pop();
    }//GEN-LAST:event_jbPopActionPerformed

    private void jbPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrintActionPerformed
        // TODO add your handling code here:
        String itens = pilha.printSwing();
        jtaPilha.setText(itens);
    }//GEN-LAST:event_jbPrintActionPerformed

    private void jbMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMaxActionPerformed
        // TODO add your handling code here:
        jtaPilha.setText(Integer.toString(pilha.returnMax()));
    }//GEN-LAST:event_jbMaxActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMinActionPerformed
        // TODO add your handling code here:
        jtaPilha.setText(Integer.toString(pilha.returnMin()));

    }//GEN-LAST:event_jbMinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPilha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPilha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPilha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPilha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPilha2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbMax;
    private javax.swing.JButton jbMin;
    private javax.swing.JButton jbPop;
    private javax.swing.JButton jbPrint;
    private javax.swing.JButton jbPush;
    private javax.swing.JButton jbSair;
    private javax.swing.JTextArea jtaPilha;
    private javax.swing.JTextField jtfElemento;
    // End of variables declaration//GEN-END:variables
}
