
import javafx.scene.input.KeyEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.event.KeyEvent.VK_ENTER;
import static java.awt.event.KeyEvent.VK_M;
import static java.awt.event.KeyEvent.VK_PLUS;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author paulo
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }
    public double parcela_1, parcela_2;
    public boolean e_sum=false, e_sub=false, e_mult=false, e_div =false, 
            e_equal=false, e_perc = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB0 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jbPlus = new javax.swing.JButton();
        jbMinus = new javax.swing.JButton();
        jbTimes = new javax.swing.JButton();
        jbDivision = new javax.swing.JButton();
        jtfVisor = new javax.swing.JTextField();
        jbEquals = new javax.swing.JButton();
        jbClear = new javax.swing.JButton();
        jbPercent = new javax.swing.JButton();
        jbRoot = new javax.swing.JButton();
        jtfVisorOperacao = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jbPoint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(255, 125, 111));

        jB0.setText("0");
        jB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB0ActionPerformed(evt);
            }
        });

        jB1.setText("1");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jB2.setText("2");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        jB3.setText("3");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });

        jB4.setText("4");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });

        jB5.setText("5");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });

        jB6.setText("6");
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });

        jB7.setText("7");
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });

        jB8.setText("8");
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });

        jB9.setText("9");
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });

        jbPlus.setText("+");
        jbPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPlusMouseClicked(evt);
            }
        });
        jbPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPlusActionPerformed(evt);
            }
        });

        jbMinus.setText("–");
        jbMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbMinusMouseClicked(evt);
            }
        });
        jbMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMinusActionPerformed(evt);
            }
        });

        jbTimes.setText("X");
        jbTimes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbTimesMouseClicked(evt);
            }
        });
        jbTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTimesActionPerformed(evt);
            }
        });

        jbDivision.setText("/");
        jbDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbDivisionMouseClicked(evt);
            }
        });
        jbDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDivisionActionPerformed(evt);
            }
        });

        jtfVisor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfVisor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfVisor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfVisorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfVisorKeyReleased(evt);
            }
        });

        jbEquals.setText("=");
        jbEquals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbEqualsMouseClicked(evt);
            }
        });
        jbEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEqualsActionPerformed(evt);
            }
        });

        jbClear.setText("AC");
        jbClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbClearMouseClicked(evt);
            }
        });
        jbClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClearActionPerformed(evt);
            }
        });

        jbPercent.setText("%");
        jbPercent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPercentMouseClicked(evt);
            }
        });
        jbPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPercentActionPerformed(evt);
            }
        });

        jbRoot.setText("√");
        jbRoot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRootMouseClicked(evt);
            }
        });
        jbRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRootActionPerformed(evt);
            }
        });

        jbPoint.setText(".");
        jbPoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPointMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfVisor)
                            .addComponent(jtfVisorOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jB4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jB5)
                                                    .addComponent(jB2)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jB7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jB8)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jB6)
                                            .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jB3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbClear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jB0, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbPoint)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jbMinus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbTimes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jbPlus)
                                    .addComponent(jbDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jB1, jB2, jB3, jB4, jB5, jB6, jB7, jB8, jB9, jbClear});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbDivision, jbMinus, jbPlus, jbTimes});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbEquals, jbPercent, jbRoot});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jtfVisorOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jB5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jB7)
                                        .addComponent(jB8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jB4)
                                    .addComponent(jB6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jB1)
                                    .addComponent(jB3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbClear, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jB0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbTimes)
                                    .addComponent(jbRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))
                            .addComponent(jbMinus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jbEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbDivision, jbMinus, jbPercent, jbPlus, jbRoot, jbTimes});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jB0, jB1, jB2, jB3, jB4, jB5, jB6, jB7, jB8, jB9, jbClear});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB0ActionPerformed
        // TODO add your handling code here:
        if (e_equal){
            jtfVisor.setText("");
            e_equal = false;
        }
        String texto_visor;
        texto_visor = jtfVisor.getText();
        jtfVisor.setText(texto_visor + "0");
    }//GEN-LAST:event_jB0ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        // TODO add your handling code here:
        if (e_equal){
            jtfVisor.setText("");
            e_equal = false;
        }
        String texto_visor;
        texto_visor = jtfVisor.getText();
        jtfVisor.setText(texto_visor + "1");
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        // TODO add your handling code here:
        if (e_equal){
            jtfVisor.setText("");
            e_equal = false;
        }        
        String texto_visor;
        texto_visor = jtfVisor.getText();
        jtfVisor.setText(texto_visor + "2");
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        // TODO add your handling code here:
        if (e_equal){
            jtfVisor.setText("");
            e_equal = false;
        }
        String texto_visor;
        texto_visor = jtfVisor.getText();
        jtfVisor.setText(texto_visor + "3");
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        // TODO add your handling code here:
        if (e_equal){
            jtfVisor.setText("");
            e_equal = false;
        }
        String texto_visor;
        texto_visor = jtfVisor.getText();
        jtfVisor.setText(texto_visor + "4");
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        // TODO add your handling code here:
        if (e_equal){
            jtfVisor.setText("");
            e_equal = false;
        }
        String texto_visor;
        texto_visor = jtfVisor.getText();
        jtfVisor.setText(texto_visor + "5");
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        // TODO add your handling code here:
        if (e_equal){
            jtfVisor.setText("");
            e_equal = false;
        }
        String texto_visor;
        texto_visor = jtfVisor.getText();
        jtfVisor.setText(texto_visor + "6");
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        // TODO add your handling code here:
        if (e_equal){
            jtfVisor.setText("");
            e_equal = false;
        }
        String texto_visor;
        texto_visor = jtfVisor.getText();
        jtfVisor.setText(texto_visor + "7");
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB8ActionPerformed
        // TODO add your handling code here:
        if (e_equal){
            jtfVisor.setText("");
            e_equal = false;
        }
        String texto_visor;
        texto_visor = jtfVisor.getText();
        jtfVisor.setText(texto_visor + "8");
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed
        // TODO add your handling code here:
        if (e_equal){
            jtfVisor.setText("");
            e_equal = false;
        }
        String texto_visor;
        texto_visor = jtfVisor.getText();
        jtfVisor.setText(texto_visor + "9");
        
    }//GEN-LAST:event_jB9ActionPerformed

    private void jbPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPlusActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbPlusActionPerformed

    private void jbEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEqualsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbEqualsActionPerformed

    private void jbDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDivisionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbDivisionActionPerformed

    private void jbTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTimesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbTimesActionPerformed

    private void jbMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMinusActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbMinusActionPerformed

    private void jbClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbClearActionPerformed

    private void jbDivisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDivisionMouseClicked
        // TODO add your handling code here:
        if(!jtfVisor.getText().isEmpty()){
        parcela_1 = Double.parseDouble(jtfVisor.getText());
        jtfVisorOperacao.setText(jtfVisor.getText() + " / ");
        jtfVisor.setText("");
        e_div = true;
        }else{
            JOptionPane.showMessageDialog(rootPane, "Por favor, insira um valor");
        }
    }//GEN-LAST:event_jbDivisionMouseClicked

    private void jbTimesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbTimesMouseClicked
        // TODO add your handling code here:
        if(!jtfVisor.getText().isEmpty()){
        parcela_1 = Double.parseDouble(jtfVisor.getText());
        jtfVisorOperacao.setText(jtfVisor.getText() + " * ");
        jtfVisor.setText("");
        e_mult = true;
        }else{
            JOptionPane.showMessageDialog(rootPane, "Por favor, insira um valor");            
        }
        
    }//GEN-LAST:event_jbTimesMouseClicked

    private void jbMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMinusMouseClicked
        // TODO add your handling code here:
        if(!jtfVisor.getText().isEmpty()){
        parcela_1 = Double.parseDouble(jtfVisor.getText());
        jtfVisorOperacao.setText(jtfVisor.getText() + " - ");
        jtfVisor.setText("");
        e_sub = true;
        }else{
            JOptionPane.showMessageDialog(rootPane, "Por favor, insira um valor");            
        }        
    }//GEN-LAST:event_jbMinusMouseClicked

    private void jbPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPlusMouseClicked
        // TODO add your handling code here:
        if(!jtfVisor.getText().isEmpty()){
        parcela_1 = Double.parseDouble(jtfVisor.getText());
        jtfVisorOperacao.setText(jtfVisor.getText() + " + ");
        jtfVisor.setText("");
        e_sum = true;
        }else{
            JOptionPane.showMessageDialog(rootPane, "Por favor, insira um valor");            
        } 
    }//GEN-LAST:event_jbPlusMouseClicked

    private void jbEqualsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEqualsMouseClicked
        // TODO add your handling code here:
        String texto_visor = jtfVisor.getText(); 
        jtfVisorOperacao.setText(jtfVisorOperacao.getText() + texto_visor);
        parcela_2 = Double.parseDouble(texto_visor);
        
        //double resultado = 0;
        if (e_sum ) {
            double soma = parcela_1 + parcela_2;
            jtfVisor.setText(Double.toString(soma));
        } else {
            if (e_sub) {
                double sub = parcela_1 - parcela_2;
                jtfVisor.setText(Double.toString(sub));
            } else {
                if (e_mult) {
                    double mult = parcela_1 * parcela_2;
                    jtfVisor.setText(Double.toString(mult));
                } else {
                    if (e_div) {
                        double div = parcela_1 / parcela_2;
                        jtfVisor.setText(Double.toString(div));
                    } else if(e_perc){
                        double perc = (parcela_1 / 100) * parcela_2;
                        jtfVisor.setText(Double.toString(perc));
                    }
                }
            }
        }
        e_sum = false; e_sub = false; e_mult = false; e_div = false;   
        e_equal = true;        
        
    }//GEN-LAST:event_jbEqualsMouseClicked

    private void jbClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbClearMouseClicked
        // TODO add your handling code here:
        jtfVisor.setText("");
        jtfVisorOperacao.setText("");

    }//GEN-LAST:event_jbClearMouseClicked

    private void jbRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRootActionPerformed

    private void jbRootMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRootMouseClicked
        // TODO add your handling code here:
        
        parcela_1 = Double.parseDouble(jtfVisor.getText());
        jtfVisorOperacao.setText("√" + jtfVisor.getText());
        double raiz = Math.sqrt(parcela_1);
        jtfVisor.setText(Double.toString(raiz));
        e_equal = true;
    }//GEN-LAST:event_jbRootMouseClicked

    private void jbPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPercentActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_jbPercentActionPerformed

    private void jbPercentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPercentMouseClicked
        // TODO add your handling code here:
        parcela_1 = Double.parseDouble(jtfVisor.getText());
        jtfVisorOperacao.setText(jtfVisor.getText() + " % ");
        jtfVisor.setText("");
        e_perc = true;
    }//GEN-LAST:event_jbPercentMouseClicked

    private void jtfVisorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfVisorKeyPressed

    }//GEN-LAST:event_jtfVisorKeyPressed

    private void jtfVisorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfVisorKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtfVisorKeyReleased

    private void jbPointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPointMouseClicked
        // TODO add your handling code here:
        String texto_visor;
        texto_visor = jtfVisor.getText();
        jtfVisor.setText(texto_visor + ".");
    }//GEN-LAST:event_jbPointMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbClear;
    private javax.swing.JButton jbDivision;
    private javax.swing.JButton jbEquals;
    private javax.swing.JButton jbMinus;
    private javax.swing.JButton jbPercent;
    private javax.swing.JButton jbPlus;
    private javax.swing.JButton jbPoint;
    private javax.swing.JButton jbRoot;
    private javax.swing.JButton jbTimes;
    private javax.swing.JTextField jtfVisor;
    private javax.swing.JTextField jtfVisorOperacao;
    // End of variables declaration//GEN-END:variables
}
