
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author paulo
 */
public class jfOperacao extends javax.swing.JFrame {

    /**
     * Creates new form jfOperacao
     */
    public jfOperacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbOK = new javax.swing.JButton();
        jtfNro1 = new javax.swing.JTextField();
        jtfNro2 = new javax.swing.JTextField();
        jtfResultado = new javax.swing.JTextField();
        jbrSoma = new javax.swing.JRadioButton();
        jbrSubtracao = new javax.swing.JRadioButton();
        jbrMultiplicacao = new javax.swing.JRadioButton();
        jbrDivisao = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operação Aritmética");

        jLabel1.setText("Número 1:");

        jLabel2.setText("Número 2:");

        jLabel3.setText("Resultado:");
        jLabel3.setToolTipText("");

        jbOK.setText("Calcular");
        jbOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbOKMouseClicked(evt);
            }
        });
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        jtfNro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNro1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jbrSoma);
        jbrSoma.setText("Soma");
        jbrSoma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbrSomaMousePressed(evt);
            }
        });

        buttonGroup1.add(jbrSubtracao);
        jbrSubtracao.setText("Subtração");
        jbrSubtracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbrSubtracaoMousePressed(evt);
            }
        });

        buttonGroup1.add(jbrMultiplicacao);
        jbrMultiplicacao.setText("Multiplicação");
        jbrMultiplicacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbrMultiplicacaoMousePressed(evt);
            }
        });
        jbrMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrMultiplicacaoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jbrDivisao);
        jbrDivisao.setText("Divisão");
        jbrDivisao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbrDivisaoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfNro2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(jtfNro1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jbrSoma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbrSubtracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbrMultiplicacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbrDivisao)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbOK)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbrSoma)
                    .addComponent(jbrSubtracao)
                    .addComponent(jbrMultiplicacao)
                    .addComponent(jbrDivisao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jbOK)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("jlNro1");
        jLabel2.getAccessibleContext().setAccessibleName("jfNro2");
        jLabel3.getAccessibleContext().setAccessibleName("jlResultado");
        jbOK.getAccessibleContext().setAccessibleName("jbOK");
        jtfNro1.getAccessibleContext().setAccessibleName("jtfNro1");
        jtfNro2.getAccessibleContext().setAccessibleName("jtfNro2");
        jtfNro2.getAccessibleContext().setAccessibleDescription("");
        jtfResultado.getAccessibleContext().setAccessibleName("jtfResultado");
        jbrSoma.getAccessibleContext().setAccessibleName("jbrSoma");
        jbrSubtracao.getAccessibleContext().setAccessibleName("jbrSubtracao");
        jbrMultiplicacao.getAccessibleContext().setAccessibleName("jbrMultiplicacao");
        jbrDivisao.getAccessibleContext().setAccessibleName("jbrDivisao");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNro1ActionPerformed

    private void jbOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbOKMouseClicked
        // TODO add your handling code here:
        jtfResultado.setText("");

        double nro1, nro2, op=0;
        if(jtfNro1.getText().isEmpty() || jtfNro2.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Por favor, insira um valor");            
        }else{
        nro1 = Double.parseDouble(jtfNro1.getText());
        nro2 = Double.parseDouble(jtfNro2.getText());
            if (jbrSoma.isSelected()) {
                op = nro1 + nro2;
                jtfResultado.setText(Double.toString(op));
            }
            if (jbrSubtracao.isSelected()) {
                op = nro1 - nro2;
                jtfResultado.setText(Double.toString(op));
            }
            if (jbrMultiplicacao.isSelected()) {
                op = nro1 * nro2;
                jtfResultado.setText(Double.toString(op));
            }
            if (jbrDivisao.isSelected()) {
                if ((nro2 == 0) || (nro1 == 0 && nro2 == 0)) {
                    JOptionPane.showMessageDialog(rootPane, "Operação inválida!");
                } else {
                    op = nro1 / nro2;
                    jtfResultado.setText(Double.toString(op));
                }
            }
        }
        
        System.out.println("BOTÃO CLICADO.");
        
    }//GEN-LAST:event_jbOKMouseClicked

    private void jbrSomaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbrSomaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbrSomaMousePressed

    private void jbrSubtracaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbrSubtracaoMousePressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jbrSubtracaoMousePressed

    private void jbrMultiplicacaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbrMultiplicacaoMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbrMultiplicacaoMousePressed

    private void jbrDivisaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbrDivisaoMousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jbrDivisaoMousePressed

    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbOKActionPerformed

    private void jbrMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrMultiplicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbrMultiplicacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfOperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfOperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfOperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfOperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfOperacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbOK;
    private javax.swing.JRadioButton jbrDivisao;
    private javax.swing.JRadioButton jbrMultiplicacao;
    private javax.swing.JRadioButton jbrSoma;
    private javax.swing.JRadioButton jbrSubtracao;
    private javax.swing.JTextField jtfNro1;
    private javax.swing.JTextField jtfNro2;
    private javax.swing.JTextField jtfResultado;
    // End of variables declaration//GEN-END:variables
}
